クラフトに時間がかかるようにするUI
moorestech/moorestech pull request #282
Opened 2024-03-08 14:43 UTC by KurisuJuha

https://www.notion.so/UI-2bc1dfab9585453c94486cb2d71d8f54

2024-03-08 17:02 UTC, sakastudio requested changes
これは伝え忘れていた仕様なので、追加で実装していただけると助かります。

- クラフトボタンからマウスカーソルが外れた時、クラフトの進行をキャンセルする
- 長押ししている間、クラフトできる間は連続してクラフトすることができる

2024-03-08 17:02 UTC, sakastudio commented on moorestech_client/Assets/Asset/Font/NotoSansJP-Medium SDF 2.asset
不要の差分かと思いますので、必要な差分以外は入れないようにお願いします。
今回はとりあえずこのままで大丈夫です。

2024-03-08 17:02 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/UI/Inventory/Sub/CraftButton.cs
> +        {
外から見た時、percentプロパティに代入し、同時に表示のアップデートが行われるというのは違和感があります。（Unityはそういうのやりがちですが、、）

`craftButton.percent = 1`となっているとき、直感的にこの処理はpercentに1を代入しただけで、その時点ではまだ変化は生じていないはずと考えやすいです。
そのため、その直感的な理解に反している可能性のあるコードは避けるべきです。

多くの場合、プロパティへの直接セットよりメソッドの実行のほうがより直感的で、外から見た時どのような挙動をするか想像がしやすいです。
例えば
`craftButton.UpdateProgress(1)` となっていれば、ボタンの進捗度合いを更新することを直感的に理解することができます。

そのため、認知負荷の低い、パッと見たときに直感的に何をしてそうかが理解できるようなコードにしていただけると助かります。

2024-03-08 17:02 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/UI/Inventory/Sub/CraftInventoryView.cs
> +
一括フォーマットはありがたいですが、レビューとして差分が見づらくなるのでフォーマット用のプルリクを別で作っていただけるとありがたいです
とりあえず今回はこのままで大丈夫です

2024-03-08 17:02 UTC, sakastudio commented on moorestech_client/Assets/Asset/Prefabs/GameSystem.prefab
こちらも不要な差分かと思います

2024-03-08 17:02 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/UI/Inventory/Sub/CraftButton.cs
> +        private void UpdateMaskFill()
ここをpublicにして、floatでpercentを取るだけでも直感的になると思います

2024-03-08 17:02 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/UI/Inventory/Sub/CraftInventoryView.cs
> +                ).AddTo(this);
基本的に私は「直感的にこのコードが何をしているのかを理解できる」ようなコードを目指しています

（これは最近始めたことなので過去に私は書いたコードはそうはなっていないわけですけれども）

UniRxというのは基本的に見た時に直感的に何をしているのか分かりづらくなる傾向にあると思っています。

例えば書いていただいたこちらのコードより、以下のようなコードの方が、実行順番や分岐が直列になっており、何をしているのかの実態が分かりやすいと思います。

```cs
            var currentCraftProgress = 0.0f;
            var craftTime = 5.0f;
            while (currentCraftProgress < craftTime)
            {
                var percent = currentCraftProgress / craftTime;
                craftButtonPercent.UpdateMaskFill(percent);
                
                currentCraftProgress += Time.deltaTime;
                await UniTask.Yield();
            }

            var recipeId = _currentCraftingConfigDataList[_currentCraftingConfigIndex].RecipeId;
            MoorestechContext.VanillaApi.SendOnly.Craft(recipeId);
```


私もそうですが、普段からUniRxを触ってない人からすると、何をしているのかを理解するために時間を要し、認知負荷の高い、非直感的なコードになってしまいがちと考えています。

そのためより認知負荷が低い、直感的なコードを書くよう意識していただけると助かります。その一環として、このようなUniRxのメソッドチェインは避けていただけると助かります。

2024-03-08 17:02 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/UI/Inventory/Sub/CraftInventoryView.cs
>          [SerializeField] private Button craftButton;
「CraftButton」クラスのフィールド名が「craftButtonPercent」であったり、同じオブジェクトを指す2つの別の方のプロパティが存在しているのはあまりよくないですね、、

クラスを分けるのであれば、そのクラスで使う機能をまとめ、外から使いやすくメソッドやreadonlyなプロパティだけを公開するほうが良いかと思います。

2024-03-09 07:06 UTC, KurisuJuha commented
修正しました。

---

> クラフトボタンからマウスカーソルが外れた時、クラフトの進行をキャンセルする

この仕様、実装してみて個人的に違和感を感じました。
Satisfactoryではクラフトボタンからカーソルが外れてもクラフトの進行は続いていました。

また、マウスカーソルがExitしたあと再度enterした際にクラフトの進行が続かないのにも違和感を感じたため、その機能も実装しました。

- カーソルが外れると経過時間がリセットされる機能
- カーソルが外れると経過時間のアップデートが止まる機能
- カーソルを戻すと経過時間のアップデートが再開する機能

の3つをインスペクタからオンオフ切り替えられるようにしました。

2024-03-09 16:09 UTC, sakastudio approved these changes
LGTM！

2024-03-09 16:10 UTC, merged