ブロックの設置可否判定
moorestech/moorestech pull request #326
Opened 2024-05-15 12:23 UTC by KurisuJuha

2024-05-15 12:47 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/IBlockPlacePreview.cs
> +        public void SetMaterial(Material material);
ここは SetPlaceablePreview(bool) のように、パラメーターを制限させてください

2024-05-15 12:52 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/BlockPlaceSystem.cs
> +            if (!IsPlaceableBlock()) return;
この3つは一つのメソッドにまとめてください

2024-05-15 12:55 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
これは何を意図した処理でしょうか？

このメソッドはサーバーから送られてきたデータをもとにGameObjectを設置するためのメソッドで、バウンディングボックスのチェックといったことは不要なような気がします

2024-05-15 12:56 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/ChunkDataHandler.cs
>      public class ChunkDataHandler : IInitializable
ChunkDataHandlerから名前変えたいですね

2024-05-15 12:57 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Starter/MainGameStarter.cs
> +        [FormerlySerializedAs("chunkBlockGameObjectDataStore")] [SerializeField]
コード上で前の名前が残っているの気持ち悪いので、特別な理由がない場合は基本これを使わず、きちんとリネームしてprefabを更新してください

2024-05-15 13:00 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Block/DetectCollisionTerrain.cs
> +        public bool isCollisionTerrain;
こういうのは IsCollisionTerrain { get; private set; }にしてください

書き込み可能なpublic変数は基本作らないでください。

2024-05-15 13:06 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/ChunkDataHandler.cs
>      public class ChunkDataHandler : IInitializable
了解です

2024-05-15 13:07 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/BlockPlaceSystem.cs
> +            DetectCollisionTerrain detectCollisionTerrain,
コリジョンの依存関係が反対でした（これは私の指示ミスです

私の想定では、ブロック側にBlockPreviewTerrainDetector.cs を持たせて、 TerrainCollison.csとの衝突を取るようにしたいです。

そうするとプレビュー側は自分が持つBlockPreviewTerrainDetector.csをリストとして持ち、毎フレーム確認するだけで済むので、依存関係や設定がシンプルになると考えています。

不明点などあれば何でも言ってください。

2024-05-15 13:07 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Starter/MainGameStarter.cs
> +        [FormerlySerializedAs("chunkBlockGameObjectDataStore")] [SerializeField]
あーRiderの一括命名変更で変えていたので気付きませんでした...
直しておきます！

2024-05-15 13:07 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Block/DetectCollisionTerrain.cs
> +        public bool isCollisionTerrain;
了解です

2024-05-15 13:10 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/IBlockPlacePreview.cs
> +        public void SetMaterial(Material material);
了解です

2024-05-15 13:13 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
こういうのはコードの意図が明確になりづらいので避けたいですね

バウンディングボックスはminとmaxの値を持つだけの存在なので、その中に埋まっている値は不要なはずです。

もしこの挙動を実装したいのであれば、

public static List<Vector3Int> GetBoundigBoxInnnerPositions(this BlockPositionInfo info){
   var result = new List<Vector3Int>();
   for (int x = info.min.x; int <= info.max.x; x++){
        // YとZの3重ループ
    }

}


などが、コードが何をしているのか直感的で、名前と照らし合わせて何が取得できるのかもすぐに理解できます。

2024-05-15 13:14 UTC, sakastudio requested changes
ざっとみてこの辺が気になりました
修正をお願いします！

2024-05-15 13:17 UTC, JuhaKurisu commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/BlockPlaceSystem.cs
> +            DetectCollisionTerrain detectCollisionTerrain,
すいません。いまいち理解できていないです。
現状BlockPlaceSystem→DetectCollisionTerrainという依存関係なのですが、その依存関係が逆とはどのような状態でしょうか？
今説明していただいた状態だと、依存関係の矢印は同じ方向な気がしています

2024-05-15 13:22 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
了解です。
確かにBoudingBoxをforeachに入れると中間値のイテレータが取れるのはかなり分かりづらかったです...

修正方針としては、BoundingBoxにGetBoundigBoxInnnerPositionIterator()のようなメソッドを生やし、その部分からBoundingBox.Enumeratorを返すようにする方針にしようと思ってますが、問題ありませんか

2024-05-15 13:23 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/BlockPlaceSystem.cs
> +            DetectCollisionTerrain detectCollisionTerrain,
今のところチェックアウトしてないので確認してないので、後で確認します
もしかしたら私が骨組みを作ったほうがいいかも

2024-05-15 13:23 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/BlockPlaceSystem.cs
> +            DetectCollisionTerrain detectCollisionTerrain,
了解です。待ちます

2024-05-15 13:24 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
[このコード](https://github.com/moorestech/moorestech/pull/326#discussion_r1601594723)と関連していると思いますが、そもそもこれってこのPRにおいて必要な処理でしたっけ？

2024-05-15 13:27 UTC, JuhaKurisu commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
まったく同じ内容の処理を2つ書くのはちょっとな...と思ったので作成しました
それがこのPRにおいて必要かと言われるとちょっと分からないですがどこかの段階では確実に必要だと思います。

2024-05-15 13:29 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
このループ、originとmaxを取るだけではダメで両方のxyzそれぞれのminとmaxを事前に取った後ループ内での値にVector3Int.Oneを足さなければならないという結構何回も書くにはキツイ内容で、そういう点から先に作成しました。

2024-05-15 13:32 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
ブロックAを置く際、既にブロックBが範囲内に置いてあることを検知するにはブロックAの範囲内のすべての位置を調べなくてはならないのでバウンディングボックスのチェックを行っています。

2024-05-15 13:37 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
そもそも、バウンディングボックスとしての情報はすでにBlockPositionInfoが持っている（クライアントで同じものを生成すればよい）ので、新たにバウンディングボックスを定義する必要はないですね

それと、今回必要なことは「あるブロックが他のブロックと被っているかどうか」ということを知りたいので、BlockPositionInfoに 

```cs
public static bool IsCollision(BlockPositionInfo target){
   //minとmaxのXYZ要素をすべて比較し、重複しているかをチェック
}
```

を実装して使えばシンプルな実装に収まると思います

2024-05-15 13:42 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
> バウンディングボックスとしての情報はすでにBlockPositionInfoが持っている

ほんとだ～～～～～～
今の今まで気づきませんでした。すいませんでした。

2024-05-15 13:45 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
> それと、今回必要なことは「あるブロックが他のブロックと被っているかどうか」ということを知りたいので、BlockPositionInfoに
（略）
を実装して使えばシンプルな実装に収まると思います

ここに関しては違うと思っています。
今回必要なことは「あるブロックが他のブロックとかぶっているかどうか」ではなく、「あるブロックの中に他のブロックがあるかどうか」です。
「あるブロックが他のブロックとかぶっているかどうか」から無理やり実装できなくもないですが、とてつもなく汚い実装になるのと、その場合の実装はO(n)なので微妙だと思っています。

2024-05-15 14:03 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/IBlockPlacePreview.cs
> +        public void SetMaterial(Material material);
https://github.com/moorestech/moorestech/pull/326/commits/f49393d43fbd9dafebc96bfdde66e1bdb6f6bcbe

2024-05-15 14:05 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/ChunkDataHandler.cs
>      public class ChunkDataHandler : IInitializable
https://github.com/moorestech/moorestech/issues/289

2024-05-15 14:06 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/ChunkDataHandler.cs
>      public class ChunkDataHandler : IInitializable
別PRで修正を行いたいのでいったんここではResolveお願いします

2024-05-15 14:09 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Starter/MainGameStarter.cs
> +        [FormerlySerializedAs("chunkBlockGameObjectDataStore")] [SerializeField]
修正しました
https://github.com/moorestech/moorestech/pull/326/commits/463ad8df5f090b14c67a570b0b5aac8a70a9b572

2024-05-15 14:09 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/IBlockPlacePreview.cs
> +        public void SetMaterial(Material material);
修正しましたー

2024-05-15 14:17 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/BlockSystem/BlockPlaceSystem.cs
> +            if (!IsPlaceableBlock()) return;
了解です。
TryGetRayHitPositionではoutパラメータがあったり、そのコードの下にブロックが置けない場合プレビューを表示する場合の早期リターンがあったりするので様式は一つに統一するべきかなと思い、あえてまとめずに置いていました。

2024-05-16 10:48 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
そこはPlaceBlockの仕事ではないですね
サーバー側のAddBlockの責務のはずです

クライアントはできる限り無知であるべきなので、サーバー側でどう扱われていようと、サーバー側が指示した通りにブロックを設置すべきです

2024-05-16 10:48 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
それはそれとして、今回のタスクはプレビューの設置可否判定なので、どちらにせよPlaceBlockで行うのは不適切です

2024-05-16 10:52 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/ChunkDataHandler.cs
>      public class ChunkDataHandler : IInitializable
OKです

2024-05-16 11:12 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
> 今回必要なことは「あるブロックが他のブロックとかぶっているかどうか」ではなく、「あるブロックの中に他のブロックがあるかどうか」です。

これである理由ってなんでしたっけ
今回の要件は他のブロックと1ブロックでもかぶさっていれば設置が不可能な見た目になることなので、かぶさっていることが求められと思います🤔

> 実装はO(n)なので微妙だと思っています。

O(n)が”微妙”かどうかはnの値で決定すべきで、おそらくどんなに多くなっても1万程度で住むはずです。

このチェックをする必要があるのはPlaceBlockPreviewの場所を移動したときと、AddBlockをしたときで、頻度としては最大で0.2秒に1回程度でしょう。となれば、現状O(n)でも暫くの間は大きな問題にならないはずです。

将来的に10万個のブロックがあるワールドが出れば問題になるかも知れませんが、それはその時にOcttreeの実装にdでも変えればいいだけの話です。

いまこのPJTはそれを考えるフェーズではありませんし、もっと他のことに注力すべきだと考えています。
私のお金も無限ではないので、シンプルで、早く実装が終わり、今後極端に悪い影響がないなら計算量が微妙でもそうするべきだと思っています。

実装は以下のようにすればシンプルで簡潔だと思うのですが、いかがですかね？
```cs
foreach (var block in _allBlock){
   if (block.posInfo.IsCollision(previewPosInfo)){
      // 設置不可能
   }
}
```

2024-05-16 11:15 UTC, KurisuJuha commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
そもそもこのコードは @sakastudio さんがもともと書いていたコードを動くように書き換えただけで処理のフローは変えないようにしています。
僕もなぜこの命名でここにこのコードがあるのだろうと思いながら書きました。
ここに違和感を感じているのは僕もなので修正するべきですが、処理のフローを変えるレベルでのリファクタはこのPRでやるべきではなく、別でissueを立て、そちらで修正するべきだと思います。

2024-05-16 11:22 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
あ〜〜すれちがい通信の理由がわかった気がする

2024-05-16 11:22 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
どうしよっかな〜〜〜

2024-05-16 11:23 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
口頭で説明するのもめんどくさいので、エンジニアとしてコードで語ります

2024-05-16 11:24 UTC, sakastudio commented on moorestech_client/Assets/Scripts/Client.Game/InGame/Chunk/BlockGameObjectDataStore.cs
> +            foreach (var position in boundingBox)
ちょっとこれは私の指示が悪かったですね
申し訳ない🙏 🙏 🙏 🙏 🙏

2024-05-16 11:25 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block.Interface/BlockPositionInfo.cs
> +        public static BlockBoundingBox GetBlockBoundingBox(Vector3Int originPosition, BlockDirection direction, Vector3Int blockSize)
いったんこっちもpendingで！！！

2024-05-16 13:47 UTC, merged