LoopGearNetworkTestが通るように修正
moorestech/moorestech pull request #340
Opened 2024-05-22 05:56 UTC by KurisuJuha

2024-05-22 07:16 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/BeltConveyor/VanillaBeltConveyorComponent.cs
> +        private readonly BlockConnectorComponent<IBlockInventory> _blockConnectorComponent;
オートフォーマッタでprivateとpublicの順番ゴチャゴチャになってる？

public → private readonly → private の順番にしたい

2024-05-22 07:17 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/BeltConveyor/VanillaBeltConveyorComponent.cs
> +        public void Destroy()
ここの順番入れ替えもオートフォーマッタ？

2024-05-22 07:19 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/Service/ConnectingInventoryListPriorityInsertItemService.cs
> +            IReadOnlyList<IBlockInventory> inventories = _blockConnectorComponent.ConnectTargets.Keys.ToArray();
色んなところでやっちゃってますけど、ToArrayとかはどこかで一掃したいですよね〜〜

2024-05-22 07:21 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/BlockConfigJsonLoad.cs
> +                if (option != null && loader != null)
option != nullはいらないです
option == null なのにローダー指定してるのはどっちかが間違っているので、明確に誤りな部分はちゃんとエラーをすろーするようにしておきたいですね

//TODO エラーログ出力する みたいなの付けておいてください

2024-05-22 07:41 UTC, sakastudio requested changes

2024-05-22 07:41 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/OptionLoader/GearConnectOption.cs
> +        public IConnectOption Load(dynamic connectorOption)
GearConnectOptionLoader と GearConnectOption を同じファイルに書いておきたい感ありますが、アセンブリ的に厳しいやつですかね

IConnectOptionLoaderをBlock.Interfaceに置けば解決する説

2024-05-22 07:41 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/BlockConfigJsonLoad.cs
> +                {
option != nullはいらないです
option == null なのにローダー指定してるのはどっちかが間違っているので、明確に誤りな部分はちゃんとエラーをすろーするようにしておきたいですね

//TODO エラーログ出力する みたいなの付けておいてください

2024-05-22 07:41 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/Param/SimpleGearGeneratorParam.cs
> +            var gearConnectSettings = BlockConfigJsonLoad.GetConnectSettings(blockParam, "gearConnects", GearConnectOptionLoader.Loader);
gearConnects、どこかにpublic const stringとして置いておきたいです

2024-05-22 07:41 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Tests/CombinedTest/Game/GearNetworkTest.cs
> +            var gearPositionD = new Vector3Int(1, 1, 0);
このパラメーター変更はまずいかも
今回の変更のテストをきちんと行えていないのでは

いままでこういう形の歯車NWだったのが
<img width="546" alt="image" src="https://github.com/moorestech/moorestech/assets/55620461/e43fd065-15cd-466b-ad81-d6b335671479">

こうなってしまっている
<img width="366" alt="image" src="https://github.com/moorestech/moorestech/assets/55620461/f2ead465-225a-4ab3-8e74-3ce0fc58dfc4">

今まではシャフト + 歯の接続のループだったのが、いまは歯での接続のループなので、今回変更した回転反転のフラグの検証ができていない

2024-05-22 07:41 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Tests/CombinedTest/Game/GearNetworkTest.cs
> +            Assert.AreEqual(true, smallGearD.IsCurrentClockwise);
これも戻す必要ありそう

2024-05-22 11:53 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/BeltConveyor/VanillaBeltConveyorComponent.cs
> +        public void Destroy()
です

2024-05-22 11:54 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/BeltConveyor/VanillaBeltConveyorComponent.cs
> +        private readonly BlockConnectorComponent<IBlockInventory> _blockConnectorComponent;
このprで修正します？
riderのオートフォーマッタがやったので今後弄ったときのためにも修正するならeditorconfigごと修正しないといけないと思ってます

2024-05-22 11:56 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/Service/ConnectingInventoryListPriorityInsertItemService.cs
> +            IReadOnlyList<IBlockInventory> inventories = _blockConnectorComponent.ConnectTargets.Keys.ToArray();
僕は必要であれば気にしないタイプですが、確かに見る側からしたら鬱陶しいですよねー

2024-05-22 11:57 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/OptionLoader/GearConnectOption.cs
> +        public IConnectOption Load(dynamic connectorOption)
かもしれないです
やってみます

2024-05-22 12:25 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/BeltConveyor/VanillaBeltConveyorComponent.cs
> +        private readonly BlockConnectorComponent<IBlockInventory> _blockConnectorComponent;
このPRでの修正は不要です（私が過去やってしまったやつものこっているので

2024-05-22 12:25 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Blocks/Service/ConnectingInventoryListPriorityInsertItemService.cs
> +            IReadOnlyList<IBlockInventory> inventories = _blockConnectorComponent.ConnectTargets.Keys.ToArray();
コード的な理由というよりは、GCが増えるので気になりポイントですね
そのうちパフォーマンスが重要になりそうなので、どこかのタイミングで一掃したいなぁ見たいな感じです

2024-05-23 05:34 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/OptionLoader/GearConnectOption.cs
> +        public IConnectOption Load(dynamic connectorOption)
DONE

2024-05-23 05:34 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/BlockConfigJsonLoad.cs
> +                {
修正しましたー

2024-05-23 05:45 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/Param/SimpleGearGeneratorParam.cs
> +            var gearConnectSettings = BlockConfigJsonLoad.GetConnectSettings(blockParam, "gearConnects", GearConnectOptionLoader.Loader);
"gearConnects"はもとからあったもので追加したわけじゃないので、Issue作って別PRでやりませんか？

2024-05-23 05:47 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Tests/CombinedTest/Game/GearNetworkTest.cs
> +            var gearPositionD = new Vector3Int(1, 1, 0);
修正しましたー

2024-05-23 05:47 UTC, KurisuJuha commented on moorestech_server/Assets/Scripts/Tests/CombinedTest/Game/GearNetworkTest.cs
> +            Assert.AreEqual(true, smallGearD.IsCurrentClockwise);
修正しましたー

2024-05-23 07:02 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Block/Config/LoadConfig/Param/SimpleGearGeneratorParam.cs
> +            var gearConnectSettings = BlockConfigJsonLoad.GetConnectSettings(blockParam, "gearConnects", GearConnectOptionLoader.Loader);
OKです

2024-05-23 07:04 UTC, sakastudio approved these changes
LGTM！！

2024-05-23 07:04 UTC, merged