Feature/train test/dijkstra test0
moorestech/moorestech pull request #450
Opened 2024-12-20 12:30 UTC by toropippi

ブロックは生成せずにとりあえずRailNodeをしいて経路探索
経路探索プログラムがあっているかのチェック
Unity C#にPriorityQueueとHeapがなかったので新規に作成している
test4つ分

2024-12-20 13:23 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Train/RailGraph/MinHeap.cs
> +public class MinHeap<T> where T : IComparable<T>
namespaceの設定をお願いします

2024-12-20 13:24 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Train/RailGraph/NOTE.md
> -## 用語定義
notionに移したという認識でOKですか？

2024-12-20 13:25 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Tests/CombinedTest/Game/SimpleTrainTest.cs
> +        {
このテストはCombinedTest（結合テスト）ではなく、UnitTest（単体テスト）側のフォルダに新しくテスト用クラスを作成して、そちらに移すようにお願いします

2024-12-20 13:25 UTC, sakastudio commented on moorestech_server/Assets/Scripts/Game.Train/RailGraph/RailGraphDatastore.cs
> +        private readonly Dictionary<RailNode, int> railIdDic;//RailNode→Id辞書。下の逆引き
後で見ます

2024-12-20 13:26 UTC, sakastudio requested changes
一旦軽く見ました
DatastoreとNodeは後で見ます！

2024-12-20 13:46 UTC, toropippi commented
Datastoreの中でRailNodeに対し0から順番にintのidを振っていますが、そこらへん可読性悪いかなとか、イマイチ自信ないです。
最初はRailNodeからの接続先を確認するのに
https://github.com/moorestech/moorestech/pull/450/commits/17d5fd0d01099cf3705b316afbb66b8d420ba353
この実装をしていました。ただどうも速度が遅く、接続先情報の管理を
RailNode.csの
public Dictionary<RailNode, int> ConnectedNodes { get; } 
から
RailGraph.csの
private readonly List<List<(int, int)>> connectNodes;
にかえたという経緯があります。

2024-12-20 13:49 UTC, toropippi commented on moorestech_server/Assets/Scripts/Game.Train/RailGraph/NOTE.md
> -## 用語定義
notionに移したという認識でOKです

2024-12-21 02:07 UTC, sakastudio approved these changes

2024-12-21 02:07 UTC, sakastudio commented
よさそうなのでヨシ

2024-12-21 02:07 UTC, merged